apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-key-2026q1
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: ssh-key-2026q1
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: value
      remoteRef:
        key: capi-provider-ssh/default/ssh-key-2026q1
        property: private_key
